version: '3'

services: 
  frontend:
    image: 'frontend-image:latest'
    container_name: frontend
    ports: 
      - 80:80
  backend:
    image: 'backend-image:latest'
    container_name: backend
    depends_on: 
      - db
    ports: 
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.4'
    container_name: db
    ports: 
      - 5432:5432
    volumes: 
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    